name: famile_massenger
description: famile_massenger

version: 0.3.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.3
  provider: ^6.0.1
  country_code_picker: ^2.0.2
  firebase_core: ^1.7.0
  pinput: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/